# Data: https://www.kaggle.com/jsphyg/weather-dataset-rattle-package?select=weatherAUS.csv

# Import data

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
data = pd.read_csv('weatherAUS - tiny.csv')

In [ ]:
data.tail()

Date      Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
9994  04/01/2012  CoffsHarbour     19.6     28.6       0.0          7.4   
9995  05/01/2012  CoffsHarbour     21.3     26.5       0.6          7.6   
9996  06/01/2012  CoffsHarbour     18.4     27.6       0.0          5.0   
9997  07/01/2012  CoffsHarbour     18.3     26.1       0.0          7.6   
9998  08/01/2012  CoffsHarbour     21.4     29.2       0.0          5.8   

      Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  \
9994      10.0          NE           56.0        NNW  ...        57.0   
9995       6.4         NNE           31.0          S  ...        70.0   
9996      10.6         SSW           56.0          N  ...        67.0   
9997       9.0          SW           28.0         SW  ...        63.0   
9998      12.8         NNE           61.0          N  ...        64.0   

      Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
9994       1015.9       1011.6       1.0       1.0     24.9     26.5   
9995       1016.1       1014.2       6.0       7.0     24.6     24.8   
9996       1011.5       1012.4       1.0       6.0     25.3     25.9   
9997       1015.6       1013.1       3.0       7.0     22.9     24.7   
9998       1010.8       1006.6       1.0       4.0     26.0     27.8   

      RainToday  RISK_MM  RainTomorrow  
9994         No      0.6            No  
9995         No      0.0            No  
9996         No      0.0            No  
9997         No      0.0            No  
9998         No      2.0           Yes  

[5 rows x 24 columns]

In [ ]:
X = data.iloc[:,:-1]

In [ ]:
X.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  01/12/2008   Albury     13.4     22.9       0.6          NaN       NaN   
1  02/12/2008   Albury      7.4     25.1       0.0          NaN       NaN   
2  03/12/2008   Albury     12.9     25.7       0.0          NaN       NaN   
3  04/12/2008   Albury      9.2     28.0       0.0          NaN       NaN   
4  05/12/2008   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RISK_MM  
0      0.0  
1      0.0  
2      0.0  
3      1.0  
4      0.2  

[5 rows x 23 columns]

# Only for this dataset, delete otherwise (Weather AUS)

X.drop('RISK_MM', axis=1, inplace=True)

In [ ]:
X.drop('RISK_MM', axis=1, inplace=True)

In [ ]:
y = data.iloc[:,-1]

In [ ]:
y.head()

0    No
1    No
2    No
3    No
4    No
Name: RainTomorrow, dtype: object

# Handling missing data - Numeric type

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

In [ ]:
#X.dtypes

In [ ]:
numerical_cols = list(np.where((X.dtypes == np.int64) | (X.dtypes == np.float64))[0])

In [ ]:
imp_mean.fit(X.iloc[:,numerical_cols])

SimpleImputer()

In [ ]:
X.iloc[:,numerical_cols] = imp_mean.transform(X.iloc[:,numerical_cols])

### Handling missing string data

In [ ]:
string_cols = list(np.where((X.dtypes == object))[0])

In [ ]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [ ]:
imp_mean.fit(X.iloc[:,string_cols])

SimpleImputer(strategy='most_frequent')

In [ ]:
X.iloc[:,string_cols] = imp_mean.transform(X.iloc[:,string_cols])

# Label encoding method

In [ ]:
def LabelEncoderMethod(series):
    from sklearn import preprocessing
    le = preprocessing.LabelEncoder()
    le.fit(series)
    #print('Actual labels',le.classes_)
    #print('Encoding values',le.transform(pd.unique(series)))
    return le.transform(series)

# Label encoding target feature

In [ ]:
y = LabelEncoderMethod(y)

In [ ]:
string_cols

[0, 1, 7, 9, 10, 21]

In [ ]:
cols = X.columns.values[string_cols]

In [ ]:
for col in cols:
    X[col] = LabelEncoderMethod(X[col])

In [ ]:
X.shape

(9999, 22)

In [ ]:
y[0:4]

array([0, 0, 0, 0])

In [ ]:
X.iloc[0:4,:]

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0    92         0     13.4     22.9       0.6     5.922649  7.782568   
1   192         0      7.4     25.1       0.0     5.922649  7.782568   
2   292         0     12.9     25.7       0.0     5.922649  7.782568   
3   392         0      9.2     28.0       0.0     5.922649  7.782568   

   WindGustDir  WindGustSpeed  WindDir9am  ...  WindSpeed3pm  Humidity9am  \
0           13           44.0          13  ...          24.0         71.0   
1           14           44.0           6  ...          22.0         44.0   
2           15           46.0          13  ...          26.0         38.0   
3            4           24.0           9  ...           9.0         45.0   

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0         22.0       1007.7       1007.1  8.000000  4.368421     16.9   
1         25.0       1010.6       1007.8  4.254275  4.368421     17.2   
2         30.0       1007.6       1008.7  4.254275  2.000000     21.0   
3         16.0       1017.6       1012.8  4.254275  4.368421     18.1   

   Temp3pm  RainToday  
0     21.8          0  
1     24.3          0  
2     23.2          0  
3     26.5          0  

[4 rows x 22 columns]

# Feature selection

In [ ]:
from sklearn.feature_selection import SelectKBest, chi2

In [ ]:
kbest = SelectKBest(score_func=chi2, k=10)

In [ ]:
from sklearn import preprocessing
MMS = preprocessing.MinMaxScaler()

In [ ]:
K_features = 5

In [ ]:
x_temp = MMS.fit_transform(X)

In [ ]:
X.head()

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0    92         0     13.4     22.9       0.6     5.922649  7.782568   
1   192         0      7.4     25.1       0.0     5.922649  7.782568   
2   292         0     12.9     25.7       0.0     5.922649  7.782568   
3   392         0      9.2     28.0       0.0     5.922649  7.782568   
4   492         0     17.5     32.3       1.0     5.922649  7.782568   

   WindGustDir  WindGustSpeed  WindDir9am  ...  WindSpeed3pm  Humidity9am  \
0           13           44.0          13  ...          24.0         71.0   
1           14           44.0           6  ...          22.0         44.0   
2           15           46.0          13  ...          26.0         38.0   
3            4           24.0           9  ...           9.0         45.0   
4           13           41.0           1  ...          20.0         82.0   

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0         22.0       1007.7       1007.1  8.000000  4.368421     16.9   
1         25.0       1010.6       1007.8  4.254275  4.368421     17.2   
2         30.0       1007.6       1008.7  4.254275  2.000000     21.0   
3         16.0       1017.6       1012.8  4.254275  4.368421     18.1   
4         33.0       1010.8       1006.0  7.000000  8.000000     17.8   

   Temp3pm  RainToday  
0     21.8          0  
1     24.3          0  
2     23.2          0  
3     26.5          0  
4     29.7          0  

[5 rows x 22 columns]

In [ ]:
x_temp = kbest.fit(x_temp,y)

In [ ]:
best_features = np.argsort(x_temp.scores_)[-K_features:]

In [ ]:
best_features

array([ 4, 18, 17, 14, 21], dtype=int64)

In [ ]:
X.columns.values[best_features]

array(['Rainfall', 'Cloud3pm', 'Cloud9am', 'Humidity3pm', 'RainToday'],
      dtype=object)

In [ ]:
features_to_delete = np.argsort(x_temp.scores_)[:-K_features]

In [ ]:
X = np.delete(X.to_numpy(), features_to_delete, axis=1)

In [ ]:
X.shape

(9999, 5)

# Conversion of MinMaxScaler object, based on KBest values
## The following object will be used in our web application

In [ ]:
__temp2 = MMS.fit_transform(X)

In [ ]:
del x_temp

In [ ]:
y[0:4]

array([0, 0, 0, 0])

# Train test split

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [ ]:
print(X_train.shape)

(7999, 5)


# Feature scaling

### Standardization: (X - mean(X)) / std(X)

### Normalization = (x - min(x)) / (max(x) - min(x))

In [ ]:
from sklearn import preprocessing

In [ ]:
sc = preprocessing.StandardScaler(with_mean=False)

In [ ]:
sc.fit(X_train)

StandardScaler(with_mean=False)

In [ ]:
X_train = sc.transform(X_train)

In [ ]:
print(X_train.shape)

(7999, 5)


In [ ]:
X_test = sc.transform(X_test)

In [ ]:
print(X_test.shape)

(2000, 5)


#### The data is ready!!

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# Building KNN model

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knnClassifier = KNeighborsClassifier(n_neighbors=3)
knnClassifier.fit(X_train,y_train)
y_pred = knnClassifier.predict(X_test)
accuracy_score(y_pred,y_test)

0.8515

# Building Logistic regression model

In [ ]:
from sklearn.linear_model import LogisticRegression
LRM = LogisticRegression(random_state=0,max_iter=200)
LRM.fit(X_train,y_train)
y_pred = LRM.predict(X_test)
accuracy_score(y_pred,y_test)

0.868

# Building GaussianNB model

In [ ]:
from sklearn.naive_bayes import GaussianNB
model_GNB = GaussianNB()
model_GNB.fit(X_train,y_train)
y_pred = model_GNB.predict(X_test)
accuracy_score(y_pred,y_test)

0.848

# Building SVM (SVC) model

In [ ]:
from sklearn.svm import SVC
model_SVC = SVC()
model_SVC.fit(X_train,y_train)
y_pred = model_SVC.predict(X_test)
accuracy_score(y_pred,y_test)

0.865

# Building Decision tree model

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model_DTC = DecisionTreeClassifier()
model_DTC.fit(X_train,y_train)
y_pred = model_DTC.predict(X_test)
accuracy_score(y_pred,y_test)

0.8315

# Building Random Forest model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_RFC = RandomForestClassifier(n_estimators = 500, max_depth= 5)
model_RFC.fit(X_train,y_train)
y_pred = model_RFC.predict(X_test)
accuracy_score(y_pred,y_test)

0.8705

# Building ADABoost model

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
model_ABC = AdaBoostClassifier()
model_ABC.fit(X_train,y_train)
y_pred = model_ABC.predict(X_test)
accuracy_score(y_pred,y_test)

0.8685

# Building XGBoost model

In [ ]:
import xgboost as xgb
model_xgb = xgb.XGBClassifier(use_label_encoder=False)
model_xgb.fit(X_train,y_train)
y_pred = model_xgb.predict(X_test)
accuracy_score(y_pred,y_test)

[21:53:03] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


0.864

In [ ]:
# Classifier object names

    # knnClassifier
    # LRM
    # model_GNB
    # model_SVC
    # model_DTC
    # model_RFC
    # model_ABC
    # model_xgb


In [ ]:
import pickle

In [ ]:
file_name = 'model_xgb'
pickle.dump(model_xgb, open(file_name, 'wb'))

In [ ]:
saved_model = pickle.load(open('model_xgb', 'rb'))


In [ ]:
# from sklearn import preprocessing
# MMS = preprocessing.MinMaxScaler()

file_name = 'MMS' # minmaxscalar object
pickle.dump(MMS, open(file_name, 'wb'))

In [ ]:
y_pred = saved_model.predict(X_test)
accuracy_score(y_pred,y_test)

0.864

In [ ]:
X_test[1]

array([0.02283472, 3.93934668, 1.95100361, 2.12694147, 0.        ])

In [ ]:
['Rainfall', 'Cloud3pm', 'Cloud9am', 'Humidity3pm', 'RainToday']

['Rainfall', 'Cloud3pm', 'Cloud9am', 'Humidity3pm', 'RainToday']